[package]
name = "demo"
version = "0.1.0"
authors = ["Luis Araya Mata <luistec2309@estudiantec.cr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
